% cd to right dir before running compile!
% if gsl is missing:
% sudo port install gsl

function compile

clc;

% mex -O -I/opt/local/include/ -L/opt/local/lib/ -lgsl -o Lattmin Lattmin.cpp energy.cpp Graph.cpp %-argcheck
% To check for alloc: ./matlab -debug -check_malloc

mex -v -output Lattmin Lattmin.cpp energy.cpp Graph.cpp ...
    CXXOPTIMFLAGS="-O3" ...
    CXXFLAGS="$CXXFLAGS -march=native -fopenmp -fPIC -std=c++17" ...
    LDFLAGS="$LDFLAGS -fopenmp" ...
    -I/usr/include ...
    -I/usr/local/include ...
    -I/usr/local/include/libigl/include ...
    -L/usr/lib:/usr/local/lib -lgsl

end